-- Changes username format: letters (any case) and numbers only, no
-- symbols (e.g. "AndyFer98"), 3-20 characters. Casing is preserved as
-- typed, but uniqueness is enforced case-insensitively so "AndyFer98"
-- and "andyfer98" can't both exist.

alter table public.profiles drop constraint profiles_username_format;
alter table public.profiles drop constraint profiles_username_key;

-- Strip the underscore separator from usernames auto-generated by the
-- 0005 backfill (e.g. "dani3l579_8ec7" -> "dani3l5798ec7"), since '_' is
-- no longer an allowed character. Must happen BEFORE the new check
-- constraint below, or adding the constraint fails against the old data.
update public.profiles
set username = regexp_replace(username, '[^A-Za-z0-9]', '', 'g')
where username is not null;

alter table public.profiles
  add constraint profiles_username_format
  check (username is null or username ~ '^[A-Za-z0-9]{3,20}$');

create unique index profiles_username_lower_idx on public.profiles (lower(username));
